/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IbadahRouteImport } from './routes/ibadah'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as DevelopmentRouteImport } from './routes/development'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffSlugRouteImport } from './routes/staff.$slug'
import { Route as CommitteeSlugRouteImport } from './routes/committee.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IbadahRoute = IbadahRouteImport.update({
  id: '/ibadah',
  path: '/ibadah',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentRoute = DevelopmentRouteImport.update({
  id: '/development',
  path: '/development',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffSlugRoute = StaffSlugRouteImport.update({
  id: '/staff/$slug',
  path: '/staff/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteeSlugRoute = CommitteeSlugRouteImport.update({
  id: '/committee/$slug',
  path: '/committee/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/development': typeof DevelopmentRoute
  '/donate': typeof DonateRoute
  '/ibadah': typeof IbadahRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/committee/$slug': typeof CommitteeSlugRoute
  '/staff/$slug': typeof StaffSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/development': typeof DevelopmentRoute
  '/donate': typeof DonateRoute
  '/ibadah': typeof IbadahRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/committee/$slug': typeof CommitteeSlugRoute
  '/staff/$slug': typeof StaffSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/development': typeof DevelopmentRoute
  '/donate': typeof DonateRoute
  '/ibadah': typeof IbadahRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/committee/$slug': typeof CommitteeSlugRoute
  '/staff/$slug': typeof StaffSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/development'
    | '/donate'
    | '/ibadah'
    | '/sitemap.xml'
    | '/committee/$slug'
    | '/staff/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/development'
    | '/donate'
    | '/ibadah'
    | '/sitemap.xml'
    | '/committee/$slug'
    | '/staff/$slug'
  id:
    | '__root__'
    | '/'
    | '/development'
    | '/donate'
    | '/ibadah'
    | '/sitemap.xml'
    | '/committee/$slug'
    | '/staff/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevelopmentRoute: typeof DevelopmentRoute
  DonateRoute: typeof DonateRoute
  IbadahRoute: typeof IbadahRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CommitteeSlugRoute: typeof CommitteeSlugRoute
  StaffSlugRoute: typeof StaffSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ibadah': {
      id: '/ibadah'
      path: '/ibadah'
      fullPath: '/ibadah'
      preLoaderRoute: typeof IbadahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development': {
      id: '/development'
      path: '/development'
      fullPath: '/development'
      preLoaderRoute: typeof DevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/$slug': {
      id: '/staff/$slug'
      path: '/staff/$slug'
      fullPath: '/staff/$slug'
      preLoaderRoute: typeof StaffSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committee/$slug': {
      id: '/committee/$slug'
      path: '/committee/$slug'
      fullPath: '/committee/$slug'
      preLoaderRoute: typeof CommitteeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevelopmentRoute: DevelopmentRoute,
  DonateRoute: DonateRoute,
  IbadahRoute: IbadahRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CommitteeSlugRoute: CommitteeSlugRoute,
  StaffSlugRoute: StaffSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
