/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MembersRouteImport } from './routes/members'
import { Route as MasalaRouteImport } from './routes/masala'
import { Route as IbadahRouteImport } from './routes/ibadah'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as DevelopmentRouteImport } from './routes/development'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffSlugRouteImport } from './routes/staff.$slug'
import { Route as CommitteeSlugRouteImport } from './routes/committee.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const MasalaRoute = MasalaRouteImport.update({
  id: '/masala',
  path: '/masala',
  getParentRoute: () => rootRouteImport,
} as any)
const IbadahRoute = IbadahRouteImport.update({
  id: '/ibadah',
  path: '/ibadah',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentRoute = DevelopmentRouteImport.update({
  id: '/development',
  path: '/development',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffSlugRoute = StaffSlugRouteImport.update({
  id: '/staff/$slug',
  path: '/staff/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteeSlugRoute = CommitteeSlugRouteImport.update({
  id: '/committee/$slug',
  path: '/committee/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/development': typeof DevelopmentRoute
  '/donate': typeof DonateRoute
  '/ibadah': typeof IbadahRoute
  '/masala': typeof MasalaRoute
  '/members': typeof MembersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/committee/$slug': typeof CommitteeSlugRoute
  '/staff/$slug': typeof StaffSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/development': typeof DevelopmentRoute
  '/donate': typeof DonateRoute
  '/ibadah': typeof IbadahRoute
  '/masala': typeof MasalaRoute
  '/members': typeof MembersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/committee/$slug': typeof CommitteeSlugRoute
  '/staff/$slug': typeof StaffSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/development': typeof DevelopmentRoute
  '/donate': typeof DonateRoute
  '/ibadah': typeof IbadahRoute
  '/masala': typeof MasalaRoute
  '/members': typeof MembersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/committee/$slug': typeof CommitteeSlugRoute
  '/staff/$slug': typeof StaffSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/development'
    | '/donate'
    | '/ibadah'
    | '/masala'
    | '/members'
    | '/sitemap.xml'
    | '/admin'
    | '/committee/$slug'
    | '/staff/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/development'
    | '/donate'
    | '/ibadah'
    | '/masala'
    | '/members'
    | '/sitemap.xml'
    | '/admin'
    | '/committee/$slug'
    | '/staff/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/development'
    | '/donate'
    | '/ibadah'
    | '/masala'
    | '/members'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/committee/$slug'
    | '/staff/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DevelopmentRoute: typeof DevelopmentRoute
  DonateRoute: typeof DonateRoute
  IbadahRoute: typeof IbadahRoute
  MasalaRoute: typeof MasalaRoute
  MembersRoute: typeof MembersRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CommitteeSlugRoute: typeof CommitteeSlugRoute
  StaffSlugRoute: typeof StaffSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masala': {
      id: '/masala'
      path: '/masala'
      fullPath: '/masala'
      preLoaderRoute: typeof MasalaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ibadah': {
      id: '/ibadah'
      path: '/ibadah'
      fullPath: '/ibadah'
      preLoaderRoute: typeof IbadahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development': {
      id: '/development'
      path: '/development'
      fullPath: '/development'
      preLoaderRoute: typeof DevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/$slug': {
      id: '/staff/$slug'
      path: '/staff/$slug'
      fullPath: '/staff/$slug'
      preLoaderRoute: typeof StaffSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committee/$slug': {
      id: '/committee/$slug'
      path: '/committee/$slug'
      fullPath: '/committee/$slug'
      preLoaderRoute: typeof CommitteeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DevelopmentRoute: DevelopmentRoute,
  DonateRoute: DonateRoute,
  IbadahRoute: IbadahRoute,
  MasalaRoute: MasalaRoute,
  MembersRoute: MembersRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CommitteeSlugRoute: CommitteeSlugRoute,
  StaffSlugRoute: StaffSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
